language: python
python:
- 3.6.1
install:
- pip install -r leaguedb/requirements.txt
script:
- date
- ls -al
- echo "secret_database_password = '$SECRET'" > leaguedb/app/password.py
- coverage run --source=.. tests.py
- coverage report
env:
  global:
    secure: EBqxqM+TC87o760qcPDy1GnHWlSbaZ0SLKLrn2Ux2P+OcNhok7FRbUa1omYhM42K360tpgDcE0QALQECX1OEIJbaBEY9RGcMR3zJAgpekYequegg71ozcbkkuezf813tyXAXZ+EzbqI/XIgLvh71zd05SIpT3jpQyOmfaUp+yKPahv8a44kT4uq27Om/oYfCutyAhm9j/gAZvTJi62a3ECX5XoU0qmT35eRozueoxy7ywyfnQHrHxh1k5Npz/H4u52+yCLhFYrE+V8vFlF7ll6dqxLivZGmQGOW+U8UE1M03mh3OugoBNtds7TtJfXObvqkoGIDTpDqcXctJnudp0xa+UfCzoK6r8C4QzZ2rAbrUTSkFMvXRu6IvsKlnfH57jXgyen2FMKd9t29pVjDowwdC5xluOoURFehcdR0M8uSPYvcszQ9M78AlFUYloHESREBN3hYkrJng9AfsirjOHte7Wy1iI8/85MnY0WKFiRMoA7WG/6/4bhRplJahjcB0d7ax2Lc0/tbmVEd/FdPvSoDVMU3GMl3xroMvDZmo47nBLbJ0KVUxujvYSGfFm/5cmqCbl8FJLT8G3m7JhFhfJoeEBOAxPNCzX9Ij6+eDaWMZSnXxn9MiAAJOFOkvdg63M5KjpudLSwbQRIhYgvBPikw/1jM5xlTeKFZyyFocFEM=
