FORMAT: 1A
HOST: http://leaguedb.me

# League DB

League DB is an API allowing players and fans of League of Legends to view different
kinds of information. All data will be in the JSON format.

## Champions [/api/champions]

### Get All Champions [GET]

Get information about every champion.

+ Response 200 (application/json)

        [
            {
                "name": "aatrox",
                "role": "top",
                "class": "skirmishers",
                "items": [
                    "bladeoftheruinedking",
                    "deathsdance",
                    ...
                ],
                "lore": "Aatrox is a legendary warrior...",
                "image": "https://ddragon.leagueoflegends.com/cdn/7.12.1/img/champion/Aatrox.png"
            },
            {
                "name": "ahri",
                "role": "mid",
                "class": "mages",
                "items": [
                    "morellonomicon",
                    "ludensecho",
                    ...
                ],
                "lore": "Unlike other foxes that roamed the woods of southern Ionia...",                
                "image": "https://ddragon.leagueoflegends.com/cdn/7.12.1/img/champion/Ahri.png"
            },
            ...
        ]

### Get A Champion By Name [GET /api/champions/{name}]

Get information about one champion by using a name parameter, which must contain only 
lowercase letters.

+ Parameters
    + name: draven

+ Response 200 (application/json)

        [
            {
                "name": "draven",
                "role": "bot",
                "class": "marksmen",
                "items": [
                    "deathsdance",
                    "statikkshiv",
                    ...
                ],
                "lore": "Unlike his brother Darius,champ victory in battle was never enough for Draven...",
                "image": "https://ddragon.leagueoflegends.com/cdn/7.12.1/img/champion/Draven.png"
            }
        ]

## Items [/api/items]

### Get All Items [GET]

Get information about all the items in the game.

+ Response 200 (application/json)

        [
            {
                "name": "statikkshiv",
                "champions": [
                    "draven",
                    "vayne",
                    ...
                ],
                "roles": [
                    "bot"
                ],
                "category": [
                    "attack_speed",
                    "nonboots_movement",
                    ...
                ],
                "image": "http://ddragon.leagueoflegends.com/cdn/7.12.1/img/item/3087.png"
            },
            {
                "name": "phantomdancer",
                "champions": [
                    "draven",
                    "vayne",
                    ...
                ],
                "category": [
                    "attack_speed",
                    "nonboots_movement",
                    ...
                ],
                "roles": [
                    "bot"
                ],
                "image": "http://ddragon.leagueoflegends.com/cdn/7.12.1/img/item/3046.png"
            }
        ]

### Get An Item by Name [GET /api/items/{name}]

Get information about an item by its name, which must contain only lowercase letters.

+ Parameters
    + name: statikkshiv

+ Response 200 (application/json)

        [
            {
                "name": "statikkshiv",
                "champions": [
                    "draven",
                    "vayne",
                    ...
                ],
                "category": [
                    "attack_speed",
                    "nonboots_movement",
                    ...
                ],
                "roles": [
                    "bot"
                ],
                "image": "http://ddragon.leagueoflegends.com/cdn/7.12.1/img/item/3087.png"
            }
        ]
        
## Classes [/api/classes]

### Get Classes [GET]

Get information of all of the classes in League of Legends.

+ Response 200 (application/json)

        [
            {
                "name": "marksman",
                "description": "Marksmen are ranged champions whose power revolves mostly around their basic attaks."
                "champions": [
                    "caitlyn",
                    "draven",
                    ...
                ],
                "items": [
                    "infinityedge",
                    "phantomdancer",
                    ...
                ],
                "image":"/images/marksman"
            },
            {
                "name": "Controller",
                "description": "Controllers are selfless champions who lack in personal power but have strong abilities that assist their teammates."
                "champions": [
                    "blitzcrank",
                    "thresh",
                    ...
                ],
                "items": [
                    "bannerofcommand",
                    "locketoftheironsolari",
                    ...
                ],
                "image":"/images/controller"
            },
            ...
        ]

### Get A Class by Name [GET /api/classes/{name}]

Get information about a class with a name parameter, which must contain only 
lowercase letters.

+ Parameters
    + name: noxus

+ Response 200 (application/json)

        [
            {
                "name": "marksman",
                "description": "Marksmen are ranged champions whose power revolves mostly around their basic attacks."
                "champions": [
                    "caitlyn",
                    "draven",
                ],
                "items": [
                    "infinityedge",
                    "phantomdancer",
                    ...
                ],
                "image":"/images/marksman"
            }
        ]

## Roles [/api/roles]

### Get Roles [GET]

Get information about all the roles in the game.

+ Response 200 (application/json)

        [
            {
                "type": "bot",
                "champions":[
                    "draven",
                    "vayne",
                    ...
                ],
                "items": [
                    "infinityedge",
                    "phantomdancer",
                    ...
                ],
                "class": "marksman",
                "image": "/static/images/bot"
            },
            {
                "type": "top",
                "champions":[
                    "renekton",
                    "riven",
                    ...
                ],
                "items": [
                    "randiunsomen",
                    "titanichydra",
                    ...
                ],
                "class": [
                    "fighter",
                    "tank"
                ],
                "image": "/images/top"
            },
            ...
        ]

### Get A Role by Type [GET /api/roles/{type}]

Get information about a role by its type, which must contain only lowercase letters.

+ Parameters
    + type: bot
+ Response 200 (application/json)

        [
            {
                "type": "bot",
                "champions":[
                    "draven",
                    "vayne",
                    ...
                ],
                "items": [
                    "infinityedge",
                    "phantomdancer",
                    ...
                ],
                "class": "marksman",
                "image": "/images/bot"
            }
        ]